gui:
  env:
    RUSTUP_HOME: '$RUNE_DATADIR/rust/rustup'
    CARGO_HOME:  '$RUNE_DATADIR/rust/cargo'
    PATH:        '$RUNE_DATADIR/rust/cargo/bin:$RUNE_DATADIR/bin:$PATH'
extensions:
  rust:
    path: '$RUNE_DATADIR/bin/extension_rust'
    config:
      lsp_path: ""
debugger:
  rust:
    command: "lldb-dap --connection connect://{addr}"
    adapter_id: "lldb"
    launch:
      request: "launch"
      type: "lldb"
      stopOnEntry: "false"
    attach:
      request: "attach"
      type: "lldb"
editor:
  icons:
    .rs: 󱘗
  comments:
    rust:
      line:
        - "//"
      block:
        - "/*"
        - "*/"
  indents:
    rust: "spaces"
